// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euqbnwukmlziicqgsikx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1cWJud3VrbWx6aWljcWdzaWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDU5OTMsImV4cCI6MjA1NjkyMTk5M30.shsFFm6xzwKfOVm9kpweCOhJhQHv2nQ4EEwEhHjGaUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);